### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by andreaskuempel** [flixlix/energy-flow-card-plus#101]
Hi;
 I have to solar converters and try to have them both in the solar view. In the original energy card it is possible the select them both. In the energy flow card plus i can onl add one entity. So I created a new entity which is the sum of both total energy entities of my converters. But in the solar field of the flow card plus the solar power is everytime 0Wh. Please help me, I tried many things for hours, but it won't will work.
 
 here is the code for my created sensor(sorry, i don't know how to add the code correctly to this message):
```
# PV_Gesamtenergie
  - name: "PV_Gesamtenergie"
    unique_id: "PV_Gesamtenergie"
    unit_of_measurement: "kWh"
    device_class: "energy"
    state_class: "total_increasing"
    state: "{{ (states('sensor.inverter_total_yield') | float + states('sensor.growatt_energy_total') | float) | round(2) }}"
```  

![image](https://github.com/flixlix/energy-flow-card-plus/assets/152437360/7a8bfcbf-fb81-4cf5-a7b1-826b9613f78c)

**Comment by nagi121** [comment]
Some Problem: Two solar inverters and no way to show the addition of both energy values.

```
- platform: template 
  sensors:
    solar_energy_total:
      friendly_name: "Solar Energie"
      unit_of_measurement: 'kWh'
      device_class: energy
      value_template: "{{ (( states('sensor.solar_dach_energy') | float(0) + states('sensor.solar_womo_energy') | float(0) )) | float }}"
```

Doing the corresponding thing with power works without problems.
