### ISSUE TITLE
[FEATURE REQUEST] - Add multiple Meters to the configuration

### ISSUE THREAD

**Issue by ChristophCaina** [flixlix/energy-flow-card-plus#138]
**Is your feature request related to a problem? Please describe.**
Currently, my Solar Setup is only providing energy to one household.
We plan to change the current setup - and connect a second household to the installation, too.

Right now, I would like to create a simulation how much of the energy of the second household COULD be covered with the current installation - but unfortunately, there's no way to implement this 'easily' in HomeAssistant.

While I could add both meters to the current Energy Dashboard, this does not take the solar Production into account in a way I would like to have it.
The current self consumed energy will only be calculated correctly, when I use the Meters from the Solar Inverter - but not, when I am using the imported / exported values from my meter.

Therefore, I thought - I might use the energy flow card plus as well as the power flow card plus to build a 'simple' flow simulation for both hoesholds.
But therefore, I would need to add multiple meters for the GRID - and yet, it seems only possible to add one Meter at all.

Also, it is (like for the HA Dashboard) not possible to calculate the self consumption based on a Solar Production and different sensors for import / export) -->

---
Using Export / Import information from the Meter (read via IR Sensor)
![image](https://github.com/user-attachments/assets/764cd65d-4caa-4497-b70b-4c8e2bf6184c)

```
type: custom:energy-flow-card-plus
entities:
  battery:
    entity:
      consumption: ''
      production: ''
  grid:
    entity:
      consumption: sensor.hm_es_tx_wm_seq3475587_caina_hm_es_tx_wm_seq3475587_1_bezug_iec_energiezahler
      production: sensor.hm_es_tx_wm_seq3475587_caina_hm_es_tx_wm_seq3475587_2_einspeisung_iec_energiezahler
    use_metadata: false
  solar:
    entity: sensor.solaredge_i1_ac_energy
    display_zero_state: true
  home: {}
  individual1: {}
clickable_entities: true
display_zero_lines: true
use_new_flow_rate_model: true
energy_date_selection: true
wh_decimals: 1
kwh_decimals: 0
min_flow_rate: 1
max_flow_rate: 6
max_expected_energy: 2000
min_expected_energy: 10
wh_kwh_threshold: 1000
```
---
Using Import / Export Data from the same Integration (SolarEdge Modbus)
![image](https://github.com/user-attachments/assets/c2a8ee56-3243-4dbb-bb88-c872880ebbd8)

```
type: custom:energy-flow-card-plus
entities:
  battery:
    entity:
      consumption: ''
      production: ''
  grid:
    entity:
      consumption: sensor.solaredge_m1_imported
      production: sensor.solaredge_m1_exported
    use_metadata: false
  solar:
    entity: sensor.solaredge_i1_ac_energy
    display_zero_state: true
  home: {}
  individual1: {}
clickable_entities: true
display_zero_lines: true
use_new_flow_rate_model: true
energy_date_selection: true
wh_decimals: 1
kwh_decimals: 0
min_flow_rate: 1
max_flow_rate: 6
max_expected_energy: 2000
min_expected_energy: 10
wh_kwh_threshold: 1000
```

**Describe the solution you'd like**
1. A way to implement more than one meter for Grid + Solar
2. it should be possible to get a correct calculation of self consumption when using information from your GRID meter - and production information from your Solar Installation.
Right now, it seems only to be the case, when export / import and production are comming from the same integration?

**Describe alternatives you've considered**

**Additional context**
