### ISSUE TITLE
[BUG] Fossil fuel always at 100%

### ISSUE THREAD

**Issue by MattJeanes** [flixlix/energy-flow-card-plus#20]
**Describe the bug**

The fossil fuel percentage / kWh always seems to be at 100% / total inbound grid energy

**To Reproduce**
1. Add official card and this card side by side
2. Configure this card with the following (supply suitable numbers for consumption/production)
```yaml
type: custom:energy-flow-card-plus
title: Day usage (new)
entities:
  fossil_fuel_percentage:
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
  grid:
    entity:
      consumption: sensor.growatt_import_from_grid_total
      production: sensor.growatt_export_to_grid_total
```
3. Observe that the low carbon always matches the grid consumption:
![image](https://github.com/flixlix/energy-flow-card-plus/assets/2363642/4768c1ff-e1ee-43c1-8a41-4d189a8e11fe)

**Expected behavior**

I expected to see the percentage / kWh of the low carbon match the official card and not always be 100%

**Screenshots**
Built-in vs new card (this repo):
![image](https://github.com/flixlix/energy-flow-card-plus/assets/2363642/e344378e-251a-4d8d-a6a6-9e84deb687bf)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 113.0.5672.127

**Smartphone (please complete the following information):**

N/A

**Additional context**

N/A

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/energy-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.
