### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by heinemannj** [flixlix/energy-flow-card-plus#3]
**Describe the bug**
 ` watt_threshold: 0`
`  kw_decimals: 2`
- only 1 decimals but I expect 2 decimals
- Grid Import is shown in Wh and not in kWh
- Low-carbon display W and not Wh

**To Reproduce**
```
  type: custom:energy-flow-card-plus
  title: Energy Flows (Today) - energy-flow-card-plus
  min_flow_rate: 3
  max_flow_rate: 10
  watt_threshold: 0
  kw_decimals: 2
  w_decimals: 2
  energy_date_selection: false
  clickable_entities: true
  entities:
    home:
      entity: sensor.house_consumption_energy_daily
      override_state: false
    solar:
      entity: sensor.solar_yield_daily
    battery:
      entity:
        consumption: sensor.battery_day_discharge_with_loss
        production: sensor.battery_day_charge_with_loss
      state_of_charge: sensor.battery_state_of_capacity
      color_circle: true
    grid:
      entity:
        consumption: sensor.power_meter_consumption_energy_daily
        production: sensor.power_meter_exported_energy_daily
    fossil_fuel_percentage:
      entity: sensor.co2_signal_grid_fossil_fuel_percentage
      icon: mdi:pine-tree
      color_icon: true
      display_zero: true
      name: Low-carbon
      state_type: power
```

**Screenshots**
![image](https://github.com/flixlix/energy-flow-card-plus/assets/3251642/8567820d-4ccf-4984-a559-8081f670e141)
![image](https://github.com/flixlix/energy-flow-card-plus/assets/3251642/edebd3fd-87a8-4995-a66a-3d701071c664)

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/energy-flow-card-plus/discussions)).

- [x] I have the latest version of the card installed.

- [x] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
I'm sorry, I forgot to update the readme. The decimals is now in energy units, so `wh_decimals` and `kwh_decimals`. Also, `watt_threshold` is now `wh_kwh_threshold`. I updated the readme now with these changes. Your configuration should work if we make these changes:

```yaml
type: custom:energy-flow-card-plus
title: Energy Flows (Today) - energy-flow-card-plus
min_flow_rate: 3
max_flow_rate: 10
wh_kwh_threshold: 0
kwh_decimals: 2
wh_decimals: 2
energy_date_selection: false
clickable_entities: true
entities:
  home:
    entity: sensor.house_consumption_energy_daily
    override_state: false
  solar:
    entity: sensor.solar_yield_daily
  battery:
    entity:
      consumption: sensor.battery_day_discharge_with_loss
      production: sensor.battery_day_charge_with_loss
    state_of_charge: sensor.battery_state_of_capacity
    color_circle: true
  grid:
    entity:
      consumption: sensor.power_meter_consumption_energy_daily
      production: sensor.power_meter_exported_energy_daily
  fossil_fuel_percentage:
    entity: sensor.co2_signal_grid_fossil_fuel_percentage
    icon: mdi:pine-tree
    color_icon: true
    display_zero: true
    name: Low-carbon
    state_type: power
```

Does this solve your issue? (At least the first two points?)

**Comment by flixlix** [comment]
Regarding your last point, this should be fixed in version 0.0.1

**Comment by flixlix** [comment]
Can you please confirm if your issue was solved?

**Comment by heinemannj** [comment]
**First two bullets are solved:**

- only 1 decimals but I expect 2 decimals
- Grid Import is shown in Wh and not in kWh

**Calculation is also OK.**
`The gap of 0.01 kWh for house comsuption` is dueto **bad** implementation of battery values within **Huawei sun2000 inverter firmware**.

**Open:**
- Low-carbon display W and not Wh

![image](https://github.com/flixlix/energy-flow-card-plus/assets/3251642/eefb1b77-a858-447d-a41f-e38a0b9f8959)

**In the readm**e the following **chapter** is missing:

**fossil_fuel_percentage**

```
          fossil_fuel_percentage:
            entity: sensor.co2_signal_grid_fossil_fuel_percentage
            icon: mdi:pine-tree
            color_icon: true
            display_zero: true
            name: Low-carbon
            state_type: kWh
```

Great - Many thanks!
