### ISSUE TITLE
[FEATURE REQUEST] Multiple solar entities

### ISSUE THREAD

**Issue by SaLuci** [flixlix/energy-flow-card-plus#37]
**Is your feature request related to a problem? Please describe.**
My solar system consists of 2 strings, so I get 2 production values. 
If I add the two values ​​via a template sensor, I lose the historical values.

**Describe the solution you'd like**
Option to enter multiple solar entities that will be added together

**Comment by flixlix** [comment]
Just released version 0.1!

It adds the option to use multiple Entities 🤩! (not only for solar 😉)
This functionality is only available in the YAML Configuration for now

**Comment by flixlix** [comment]
I tested this with a list of entities, where one of the was unavailable and I didn't notice any issues, it gets handled as 0.
Templating is only going to be added to the secondary_info. It also wouldn't  work with the date selection, so...
Can you send me the code for your card, where you're experiencing this?

**Comment by lucasimons** [comment]
How can i add my 3 solar system to this card?   the original card do the sum of three sensor.


I would do the same with the individual2, because i have 3 different device in energy dashboard
```
type: custom:energy-flow-card-plus
entities:
  battery:
    entity:
      consumption: sensor.daily_battenergydischarged
      production: sensor.daily_battenergycharged
  grid:
    entity:
      consumption: sensor.energia_giornaliera
  individual2:
    entity:
      - sensor.daily_pdc
      - sensor.daily_resistenza
      - sensor.daily_resistenza_solare
    icon: mdi:water
    color: '#80b8ff'
    color_icon: false
  individual1:
    entity: sensor.monthly_peugeot
    icon: mdi:car-electric
    color: '#80b8ff'
    display_zero: true
    color_icon: false
  solar:
    entity:
      - sensor.daily_pvenergy
      - sensor.daily_fvenergy
      - sensor.daily_fv3energyenergy
clickable_entities: true
display_zero_lines: true
use_new_flow_rate_model: true
energy_date_selection: true
wh_decimals: 1
kwh_decimals: 0
min_flow_rate: 1
max_flow_rate: 6
max_expected_energy: 2000
min_expected_energy: 10
wh_kwh_threshold: 1000

```

![image](https://github.com/flixlix/energy-flow-card-plus/assets/67467751/6cd9ff2b-41d3-4423-a4dc-39a2a416b865)
bottom left side energy-flow-card-plus bottom right side energy-flow-card
![image](https://github.com/flixlix/energy-flow-card-plus/assets/67467751/798e7b05-bae2-4c33-8c45-15c9718b1c33)

@SaLuci do you have sove it?
