### ISSUE TITLE
[OTHER]How to setup Yaml configuriation and override sensors in Energy dashboard?

### ISSUE THREAD

**Issue by flyzet-prog** [flixlix/energy-flow-card-plus#5]
Hi, can't configure Energy dashboard. Instaled successfully via HACS, found .js file /config/www/community/energy-flow-card-plus/energy-flow-card-plus.js, but don't know where to put yaml config code to change the sensors in Energy dashboard. Can you please guide me in the right way? 
Thanks

**Comment by flixlix** [comment]
This card is not supposed to be placed directly in the energy Dashboard, instead place it in a normal dashboard. Here you can still replicate the energy dashboard, by using a combination of this card ans the [energy cards](https://www.home-assistant.io/dashboards/energy/).

In your dashboard, click on the three dots at the top right and click "Edit Dashboard", add a card, by clicking the + button in the lower right and select the energy flow card plus from the list. From there on you should be able to edit the configuration of your card.

**Comment by flyzet-prog** [comment]
Unfortunately,  want to replace the energy dashboard because the power flow card on main dashboard calculates home consumption in my case from the ac_output_active power sensor of my inverter and place all data into pv_energy_today.
But in the energy dashboard it's simply subtracting battery production and consumption difference from pv energy today, and showing me house consumption. So, I don't know which one is more correct will be. But, as I understand there is no option to change sensors in the energy dashboard for now.
<img width="1178" alt="Screenshot 2023-05-12 at 16 05 55" src="https://github.com/flixlix/energy-flow-card-plus/assets/73076482/4454884f-7063-4993-b6c0-b2ec525e59f1">
<img width="800" alt="Screenshot 2023-05-12 at 16 06 11" src="https://github.com/flixlix/energy-flow-card-plus/assets/73076482/d247730c-d740-487b-8977-35da82e7ba0d">

**Comment by flyzet-prog** [comment]
for sure, but i need all graphs and all staff on the energy dashboard as well, I like it and it's enough informative. There are any way to put them all in new energy dashboard?

**Comment by flyzet-prog** [comment]
I did exactly how you mentioned before, but it's not adding into database of calendar my house sensor unfortunately, maybe you know some way to make it? Please check on screenshots, difference from May 11 and May 12. Much appreciated for you help
<img width="1182" alt="Screenshot 2023-05-12 at 17 07 09" src="https://github.com/flixlix/energy-flow-card-plus/assets/73076482/f2733262-6047-45ba-9d50-83cd14cf022c">
<img width="1182" alt="Screenshot 2023-05-12 at 17 07 22" src="https://github.com/flixlix/energy-flow-card-plus/assets/73076482/fabcb8fa-5115-45cb-8dfa-ba569b638422">

**Comment by flyzet-prog** [comment]
the main thing is that I want to override values from the default calculation of the house to my custom sensor that I created recently

**Comment by flixlix** [comment]
[energy-flow-card-plus.js.zip](https://github.com/flixlix/energy-flow-card-plus/files/11465807/energy-flow-card-plus.js.zip)
Can you please try this file?

Your config should look something like this:

```yaml
type: custom:energy-flow-card-plus
entities:
  grid:
    entity:
      consumption: sensor.grid_consumed_energy
      production: sensor.grid_returned_energy
  solar:
    entity: sensor.solar_energy
  battery:
    entity:
      consumption: sensor.battery_out_energy
      production: sensor.battery_in_energy
  individual1:
    entity: sensor.scooter_energy
    icon: mdi:motorbike-electric
  individual2:
    entity: sensor.car_energy
  fossil_fuel_percentage:
    entity: sensor.fossil_fuel_percentage
    icon: mdi:pine-tree
    color_icon: true
    display_zero: true
    name: Low-carbon
  home:
    entity: sensor.home_energy
    override_state: true
wh_kwh_threshold: 0
kwh_decimals: 1
energy_date_selection: false
clickable_entities: true
use_new_flow_rate_model: false

```
