### ISSUE TITLE
[OTHER] Energy Date Selection on secondary obj want update sensor info

### ISSUE THREAD

**Issue by flyzet-prog** [flixlix/energy-flow-card-plus#51]
Hello dear developer. I Have been tested secondary info with my sensors, and it won’t track them every hour, day etc. always see zero. Energy date selection enabled. The sensors updates as should be.
please help me to resolve this issue.
Tried in different ways, no luck
![5F07C871-AD85-4A85-B48D-41FE745CCA18](https://github.com/flixlix/energy-flow-card-plus/assets/73076482/e32c671a-0f66-4c20-884a-822ae970dfc8)

**Comment by flixlix** [comment]
Can you try setting the same entity for the solar field and secondary info? That way, you can make sure if the current secondary info. entity has any statistics being recorded

**Comment by flyzet-prog** [comment]
If entity the same they shows the same values and updates both, but as soon if i chose different sensors secondary object sensor wan’t update. Hope this helps some how

**Comment by flixlix** [comment]
Alright, this means that the entity that doesn't work is not being saved to statistics.
For it to be tracked, make sure the entity follows the requirements:
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by flyzet-prog** [comment]
> Alright, this means that the entity that doesn't work is not being saved to statistics.
> For it to be tracked, make sure the entity follows the requirements:
> https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

It’s obvious that my sensors is saved to statistic. Kindly check my screenshots bellow. Bellow you can see energy devices graph Jun 10(emty), and today Jun 11 already populating. 
![9E57DB91-75C0-43D9-8215-7AA7DCCB2726](https://github.com/flixlix/energy-flow-card-plus/assets/73076482/6ec54999-3a88-41a3-b606-67347e99bbd5)
![3A6E98AC-DFF8-49B7-A5DE-D03C71F97100](https://github.com/flixlix/energy-flow-card-plus/assets/73076482/fc163393-0888-4e77-8a8b-7489a537b37a)
![266AA2DE-CBEE-4DE6-A641-E2E6F338AD86](https://github.com/flixlix/energy-flow-card-plus/assets/73076482/505ba764-f754-4c24-870b-04facb520f39)

**Comment by flixlix** [comment]
Can you send me the code you are using?

**Comment by flyzet-prog** [comment]
Of course, here is the code bellow 
```

type: custom:energy-flow-card-plus
entities:
  grid:
    entity:
      consumption: sensor.z_merezhi_za_den
    display_state: one_way
    power_outage: {}
    secondary_info:
      entity: sensor.s3
      unit_of_measurement: Uah
      energy_date_selection: true
      display_zero: false
      icon: mdi:currency-uah
      unit_white_space: false
    invert_state: false
  solar:
    entity: sensor.pv_energy_today
    secondary_info:
      unit_of_measurement: Uah
      icon: mdi:currency-uah
      display_zero: false
      unit_white_space: false
      entity: sensor.s1
      energy_date_selection: true
    display_zero_state: true
  battery:
    entity:
      consumption: sensor.battery_consumption
      production: sensor.battery_production
  home:
    override_state: true
    entity: sensor.house
    secondary_info:
      icon: mdi:currency-uah
      display_zero: false
      clickable_entitie: true
      unit_white_space: false
      entity: sensor.s2
      unit_of_measurement: Uah
      energy_date_selection: true
  individual1:
    entity: sensor.boiler_socket_energy_meter
    name: Water heater
    color_icon: true
    color_value: false
    display_zero_state: true
    decimals: 2
    icon: mdi:water-boiler
    use_metadata: false
    color:
      - 63
      - 132
      - 198
    display_zero: true
    secondary_info:
      unit_of_measurement: Uah
      unit_white_space: false
      display_zero: false
      icon: mdi:currency-uah
      energy_date_selection: true
      entity: sensor.s4
  individual2:
    entity: sensor.conditioner_socket_energy_meter
    display_zero: true
    use_metadata: false
    icon: mdi:air-conditioner
    name: Air conditioner
    inverted_animation: false
    decimals: 2
    display_zero_state: true
    color_value: false
    secondary_info:
      unit_of_measurement: Uah
      display_zero: false
      unit_white_space: false
      icon: mdi:currency-uah
      energy_date_selection: true
      entity: sensor.s5
kwh_decimals: 2
energy_date_selection: true
clickable_entities: true
use_new_flow_rate_model: true
display_zero_lines: false
wh_decimals: 2

```
