### ISSUE TITLE
[OTHER] Wrong daily values

### ISSUE THREAD

**Issue by Veuchez** [flixlix/energy-flow-card-plus#54]
I don't understand if I'm wrong in the configuration of the sensors, the card or something else, can you help me please?
I have a connected Huawei system with Huawei Solar integration.
The battery sensor has negative and positive values ​​as well as the grid sensor.
I then separated the values ​​to keep them positive only.

```
sensor:
  - platform: template
    sensors:    
      ricarica_batteria:
        value_template: "{{ (states('sensor.battery_charge_discharge_power')|float) if states('sensor.battery_charge_discharge_power')|float > 0 else 0 }}"
        device_class: power
        unit_of_measurement: W

      scarica_batteria:
        value_template: "{{ (-1*(states('sensor.battery_charge_discharge_power')|float)) if states('sensor.battery_charge_discharge_power')|float < 0 else 0 }}"
        device_class: power
        unit_of_measurement: W

      consumo_rete:
        value_template: "{{ 0 if states('sensor.power_meter_active_power')|float < 0 else states('sensor.power_meter_active_power')|float }}"
        device_class: power
        unit_of_measurement: W

      immissione_rete:
        value_template: "{{ (-1*(states('sensor.power_meter_active_power')|float)) if states('sensor.power_meter_active_power')|float < 0 else 0 }}"
        device_class: power
        unit_of_measurement: W
```

I then created the sensors in kWh

```
sensor:
  - platform: integration
    source: sensor.inverter_input_power
    name: produzione_pannelli_kwh
    unit_prefix: k
    unit_time: h
    round: 2

  - platform: integration
    source: sensor.consumo_rete
    name: consumo_rete_kwh
    unit_prefix: k
    unit_time: h
    round: 2

  - platform: integration
    source: sensor.immissione_rete
    name: immissione_rete_kwh
    unit_prefix: k
    unit_time: h
    round: 2

  - platform: integration
    source: sensor.inverter_active_power
    name: consumo_totale_kwh
    unit_prefix: k
    unit_time: h
    round: 2

  - platform: integration
    source: sensor.ricarica_batteria
    name: ricarica_batteria_kwh
    unit_prefix: k
    unit_time: h
    round: 2

  - platform: integration
    source: sensor.scarica_batteria
    name: scarica_batteria_kwh
    unit_prefix: k
    unit_time: h
    round: 2

```
From these sensors I created the daily sensors

```
utility_meter:
  produzione_giornaliera_pannelli_kwh:
    source: sensor.produzione_pannelli_kwh
    cycle: daily

  consumo_giornaliero_batteria_kwh:
    source: sensor.scarica_batteria_kwh
    cycle: daily

  ricarica_giornaliera_batteria_kwh:
    source: sensor.ricarica_batteria_kwh
    cycle: daily

  consumo_giornaliero_totale_kwh:
    source: sensor.consumo_totale_kwh
    cycle: daily

  consumo_giornaliero_rete_kwh:
    source: sensor.consumo_rete_kwh
    cycle: daily

  immissione_giornaliera_rete_kwh:
    source: sensor.immissione_rete_kwh
    cycle: daily
```

and customized the various sensors with unit of measure and class

```
homeassistant:
  customize:
    sensor.produzione_giornaliera_pannelli_kwh:
      unit_of_measurement: kWh
      device_class: energy

    sensor.consumo_giornaliero_batteria_kwh:
      unit_of_measurement: kWh
      device_class: energy

    sensor.ricarica_giornaliera_batteria_kwh:
      unit_of_measurement: kWh
      device_class: energy

    sensor.consumo_giornaliero_totale_kwh:
      unit_of_measurement: kWh
      device_class: energy

    sensor.consumo_giornaliero_rete_kwh:
      unit_of_measurement: kWh
      device_class: energy

    sensor.immissione_giornaliera_rete_kwh:
      unit_of_measurement: kWh
      device_class: energy

    sensor.consumo_giornaliero_totale_kwh_qubino:
      unit_of_measurement: kWh
      device_class: energy
```

This is my card setup

```
type: custom:energy-flow-card-plus
entities:
  solar:
    entity: sensor.produzione_giornaliera_pannelli_kwh
    display_zero_state: true
  battery:
    entity:
      consumption: sensor.consumo_giornaliero_batteria_kwh
      production: sensor.ricarica_giornaliera_batteria_kwh
  grid:
    entity:
      consumption: sensor.consumo_giornaliero_rete_kwh
      production: sensor.immissione_giornaliera_rete_kwh
energy_date_selection: true
clickable_entities: true
display_zero_lines: true
use_new_flow_rate_model: true
wh_decimals: 1
kwh_decimals: 2
min_flow_rate: 1
max_flow_rate: 6
max_expected_energy: 7000
min_expected_energy: 0
wh_kwh_threshold: 0
```

and this is the wrong data i get

![energy](https://github.com/flixlix/energy-flow-card-plus/assets/59020055/e852fc63-fb9e-4322-ba00-20d3f8c3f3df)

In the official energy panel the data is correct

![energy official](https://github.com/flixlix/energy-flow-card-plus/assets/59020055/679765c2-c973-4e70-b1b6-fbf0a47fd570)

Do you see something wrong by any chance?
Thank you!

**Comment by flixlix** [comment]
Hey there 👋,
your configuration for the sensors looks exactly like how I would do it, there's probably nothing wrong there...
Are you using the daily sensors for the energy integration?
Do you see any change in values when you set `energy_date_selection: false`?
Both grid sensors and the battery export sensor seem to be showing the correct values, just rounded to two decimals instead of one... So the only sensors showing the incorrect values are the battery import and the solar production...
When you import the `type: energy-distribution` card, what values are shown then?

**Comment by Veuchez** [comment]
Yes, I'm using the daily sensors.
The only problem on the daily sensors that I can't figure out is that this doesn't build, it's like there's something wrong with the code.
```
utility_meter:
  ricarica_giornaliera_batteria_kwh:
    source: sensor.ricarica_batteria_kwh
    cycle: daily
```
So as battery charge sensor currently, until I find the error on the daily sensor, I use the total sensor

```
sensor:
  - platform: integration
    source: sensor.ricarica_batteria
    name: ricarica_batteria_kwh
    unit_prefix: k
    unit_time: h
    round: 2
```

These are the data shown on your card (If I click on the circle, the history opens with the right data)
![enrgy custom](https://github.com/flixlix/energy-flow-card-plus/assets/59020055/34aa8f09-bfbd-459d-a3d6-64039406560d)

These are the data reported by the official card, with the same sensors:
![energy](https://github.com/flixlix/energy-flow-card-plus/assets/59020055/3ad34861-edee-4b99-bfef-92cc3a7c8a31)
