### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mihmihmih1988** [flixlix/energy-flow-card-plus#57]
**Describe the bug**
unable to control the number of digits of secondary entity for solar.
I configured entity for 1 digit but card keeps displaying 3 digits

**To Reproduce**
I use the solar forecast integration that is integrated with HA energy dashboard
sensor.energy_production_today
and copy past it in the card.

```yaml
type: custom:energy-flow-card-plus
entities:
  grid:
    name: Grid
    icon: mdi:transmission-tower
    color_icon: false
    color_circle: true
    color:
      production:
        - 244
        - 182
        - 11
      consumption:
        - 64
        - 177
        - 247
    entity:
      consumption: sensor.p1_meter_total_power_import_day
      production: sensor.p1_meter_total_power_export_day
  solar:
    entity: sensor.solar_meter_day_from_w
    display_zero_state: true
    icon: mdi:white-balance-sunny
    color_value: true
    color_icon: true
    color:
      - 244
      - 182
      - 11
    secondary_info:
      entity: sensor.sensor_energy_forecast_today_mppt1_2
      unit_of_measurement: kWh
      display_zero: true
  individual1:
    entity: sensor.nous_socket_airco_summation_delivered
    name: Airco
    icon: mdi:ev-station
    color_value: true
    color_icon: true
    color:
      - 56
      - 199
      - 47
    display_zero: true
  individual2:
    entity: sensor.shelly_jacuzzi_energy
    name: Jacuzzi
    icon: mdi:pool
    color_value: true
    color_icon: true
    color:
      - 56
      - 199
      - 47
    display_zero: true
clickable_entities: true
display_zero_lines: true
use_new_flow_rate_model: true
energy_date_selection: true
wh_decimals: 0
kwh_decimals: 1
min_flow_rate: 1
max_flow_rate: 6
max_expected_energy: 50000
min_expected_energy: 1
wh_kwh_threshold: 0
```

**Expected behavior**
I expect to see 1 digit kWh

**Screenshots**
![image](https://github.com/flixlix/energy-flow-card-plus/assets/127425565/ec6b74e0-7ee0-4dfe-af91-fcc67cdf38c7)
![image](https://github.com/flixlix/energy-flow-card-plus/assets/127425565/b127d5f1-751a-4a55-91cd-d3c1954159b8)
![image](https://github.com/flixlix/energy-flow-card-plus/assets/127425565/4ab58fa3-3731-45a1-bdec-74479c230cac)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [x ] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/energy-flow-card-plus/discussions)).

- [x ] I have the latest version of the card installed.

- [x ] I have cleared my browser cache **after** installing, updating and configuring the card.
