### ISSUE TITLE
[BUG] Card shows wrong unit_of_measurement value

### ISSUE THREAD

**Issue by intragart** [flixlix/energy-flow-card-plus#95]
**Describe the bug**
The data units shown in the card show `Wh` while the `unit_of_measurement` for the entities say `kW`. 

**To Reproduce**
1. Have integration that delivers measurements with `kW` as `unit_of_measurement`
2. Set up Energy Flow Card Plus (see "Additional Context" for configuration)
3. Wrong `unit_of_measurement` is shown in Card

**Expected behavior**
Show data units in card based on `unit_of_measurement` of entity

**Screenshots**
![grafik](https://github.com/flixlix/energy-flow-card-plus/assets/82698121/e219e081-5071-46ad-a60f-975d80e6347d)
![grafik](https://github.com/flixlix/energy-flow-card-plus/assets/82698121/752bca42-1ce6-4895-bcf2-2fc18a801be5)

**Desktop**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 119.0.2151.44

**Additional context**
```yaml
type: custom:energy-flow-card-plus
entities:
  battery:
    entity:
      consumption: sensor.senec_webapi_accuimport_now
      production: sensor.senec_webapi_accuexport_now
    state_of_charge: sensor.senec_webapi_acculevel_now
    state_of_charge_unit_white_space: false
  grid:
    entity:
      consumption: sensor.senec_webapi_gridimport_now
      production: sensor.senec_webapi_gridexport_now
    use_metadata: false
    secondary_info: {}
  solar:
    entity: sensor.senec_webapi_powergenerated_now
    display_zero_state: true
  home:
    entity: sensor.senec_webapi_consumption_now
    override_state: false
  individual1: {}
clickable_entities: true
display_zero_lines: true
use_new_flow_rate_model: true
energy_date_selection: false
wh_decimals: 2
kwh_decimals: 2
min_flow_rate: 1
max_flow_rate: 6
max_expected_energy: 2000
min_expected_energy: 10
title: Aktuelle Energieverteilung
wh_kwh_threshold: 1000
dashboard_link: /energy
mwh_decimals: 2
kwh_mwh_threshold: 1000
```

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [ x ] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/energy-flow-card-plus/discussions)).

- [ x ] I have the latest version of the card installed.

- [ x ] I have cleared my browser cache **after** installing, updating and configuring the card.
